# Dockerのバージョン
version: '3'

services:
  nuxt:
    container_name: sinohiroHP
    build: ./sinohiroHP
  
    # イメージ名
    image: nuxt_app_image
  
    # ホストOSとコンテナ内でソースコードを共有
    volumes:
     - ./sinohiroHP:/app
    tty: true
  
    # コンテナ内部の3000を外部から3000でアクセス
    ports:
     - "3000:3000"
    
    restart: always

  php:
    image: php:7-fpm
    container_name: php7.2
    volumes: 
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
  
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL2:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/server.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./sinohiroHP/dist:/var/www/html
    command: ["--version"]

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    build:
      context: ./nginx/nextcloud
    volumes:
      - nextcloud:/var/www/html
      - ./php/max-execution-time.ini:/usr/local/etc/php/conf.d/max-execution-time.ini
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - OVERWRITEWEBROOT=/nextcloud
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=51200M
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=127.0.0.1
    env_file:
      - ./mariadb/db.env
    restart: always
  
  db:
    container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass6854
    env_file:
      - ./mariadb/db.env
    restart: always

  #dns:
  #  build: .
  #  ports:
  #    - "53:53/udp"
  #    - "53:53/tcp"
  #  restart: always
  #  dns:
  #    - 8.8.8.8
  #    - 8.8.4.4
  #  extra_hosts:
  #    - "sinohiro.dip.jp:192.168.1.2"
  #  cap_add:
  #    - NET_ADMIN

volumes:
  nextcloud: 
    driver_opts:
      type: none
      device: /mnt/web/sinohiroHP-docker/nextcloud
      o: bind
  db: 
    driver_opts:
      type: none
      device: /mnt/web/sinohiroHP-docker/mariadb
      o: bind
