# Dockerのバージョン
version: '3'

services:
  # nuxt:
  #   container_name: sinohiroHP
  #   build: ./sinohiroHP
  # 
  #   # イメージ名
  #   image: nuxt_app_image
  # 
  #   # ホストOSとコンテナ内でソースコードを共有
  #   volumes:
  #    - ./sinohiroHP:/app
  #   tty: true
  # 
  #   # コンテナ内部の3000を外部から3000でアクセス
  #   ports:
  #    - "3000:3000"
  #   
  #   restart: always

  php:
    image: php:7-fpm
    container_name: php7.2
    volumes: 
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
  
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - OVERWRITEWEBROOT=/nextcloud
    env_file:
      - ./mariadb/db.env
    restart: always

  
  db:
    container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass6854
    env_file:
      - ./mariadb/db.env
    restart: always

volumes:
  nextcloud: 
    driver_opts:
      type: none
      device: /home/sinohiro/docker/sinohiroHP-docker/nextcloud
      o: bind
  db: 
    driver_opts:
      type: none
      device: /home/sinohiro/docker/sinohiroHP-docker/mariadb
      o: bind