# Dockerのバージョン
version: '3'

services:
  nuxt:
    container_name: sinohiroHP
    build: ./sinohiroHP

    # イメージ名
    image: nuxt_app_image

    # ホストOSとコンテナ内でソースコードを共有
    volumes:
     - ./sinohiroHP:/app
    tty: true

    # コンテナ内部の9000を外部から9000でアクセス
    ports:
     - "3000:3000"
    
    restart: always

  php:
    image: php:7-fpm
    container_name: php7.2
    volumes: 
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./php/php.ini:/usr/local/etc/php/php.ini
  
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxt
    
    restart: always