# Dockerのバージョン
version: '3'

services:
  nuxt:
    container_name: sinohiroHP
    build: ./sinohiroHP

    # イメージ名
    image: nuxt_app_image

    # ホストOSとコンテナ内でソースコードを共有
    volumes:
     - ./sinohiroHP:/app
    tty: true

    # コンテナ内部の9000を外部から9000でアクセス
    ports:
     - "3000:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxt
