version: '3'
services:
  # nuxt:
  #   container_name: build-sinohiroHP
  #   build: ./sinohiroHP
  
  #   # イメージ名
  #   image: nuxt_app_image
  
  #   # ホストOSとコンテナ内でソースコードを共有
  #   volumes:
  #    - ./sinohiroHP:/app
  #   tty: true
  
  #   # コンテナ内部の3000を外部から3000でアクセス
  #   ports:
  #    - "3000:3000"
    
  #   restart: always

  sinohiro-HP:
    container_name: sinohiro-HP
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=sinohiro.f5.si, 192.168.1.*, sinohiro.dip.jp
      - LETSENCRYPT_HOST=sinohiro.f5.si
      - LETSENCRYPT_EMAIL=sinohiro966@gmail.com
    volumes:
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL2:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/server.conf

  php:
    container_name: php7.2
    image: php:7-fpm
    restart: always
    volumes: 
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./php/php.ini:/usr/local/etc/php/php.ini

# volumes:
  # geekcast: 
  #   driver_opts:
  #     type: none
  #     device: /mnt/sinohiro-server_storage/sinohiroHP-docker/geekcast
  #     o: bind
  # geekcast-db: 
  #   driver_opts:
  #     type: none
  #     device: /mnt/sinohiro-server_storage/sinohiroHP-docker/geekcast-db
  #     o: bind
  # u16procon: 
  #   driver_opts:
  #     type: none
  #     device: /mnt/sinohiro-server_storage/sinohiroHP-docker/u16procon
  #     o: bind
  # u16procon-db: 
  #   driver_opts:
  #     type: none
  #     device: /mnt/sinohiro-server_storage/sinohiroHP-docker/u16procon-db
  #     o: bind
