version: '3'
services:
  nuxt:
    container_name: build-sinohiroHP
    build: ./sinohiroHP
  
    # イメージ名
    image: nuxt_app_image
  
    # ホストOSとコンテナ内でソースコードを共有
    volumes:
     - ./sinohiroHP:/app
    tty: true
  
    # コンテナ内部の3000を外部から3000でアクセス
    ports:
     - "3000:3000"
    
    restart: always

  sinohiro-HP:
    container_name: sinohiro-HP
    image: nginx:latest
    restart: always
    ports:
      - "80"
    networks:
      - docker-network
    environment:
      - VIRTUAL_HOST=sinohiro.f5.si, 192.168.1.*, sinohiro.dip.jp
      - LETSENCRYPT_HOST=sinohiro.f5.si
      - LETSENCRYPT_EMAIL=sinohiro966@gmail.com
    volumes:
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL2:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/server.conf
  php:
    container_name: php7.2
    image: php:7-fpm
    restart: always
    networks:
      - docker-network
    volumes: 
      - ./sinohiroHP/dist:/var/www/html
      - ./nginx/Build_WebGL:/var/www/html/Build_WebGL
      - ./nginx/speedtest:/var/www/html/speedtest
      - ./php/php.ini:/usr/local/etc/php/php.ini

  nextcloud:
    build:
      context: ./nginx/nextcloud
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - "80"
    networks:
      - docker-network
    environment:
      - MYSQL_HOST=db
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=51200M
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=127.0.0.1
      - VIRTUAL_HOST=ecloud.sinohiro.f5.si
      - LETSENCRYPT_HOST=ecloud.sinohiro.f5.si
      - LETSENCRYPT_EMAIL=sinohiro966@gmail.com
    volumes:
      - nextcloud:/var/www/html
      - ./php/max-execution-time.ini:/usr/local/etc/php/conf.d/max-execution-time.ini
    links:
      - db
  db:
    container_name: db
    image: mariadb
    restart: always
    networks:
      - docker-network
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    env_file:
      - nc.env
    volumes:
      - db:/var/lib/mysql

  geekcast:
    container_name: geekcast
    image: wordpress:latest
    restart: always
    ports:
      - "80"
    networks:
      - docker-network
    environment:
      - WORDPRESS_DB_HOST=geekcast-db:3306
      - WORDPRESS_DB_USER=sinohiro
      - WORDPRESS_DB_PASSWORD=Pass.6854
      - VIRTUAL_HOST=blog.sinohiro.f5.si
      - LETSENCRYPT_HOST=blog.sinohiro.f5.si
      - LETSENCRYPT_EMAIL=sinohiro966@gmail.com
    volumes:
      - geekcast:/var/www/html
    links:
      - geekcast-db
  geekcast-db:
    container_name: geekcast-db
    image: mariadb
    restart: always
    volumes:
      - geekcast-db:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=Pass.6854
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=sinohiro
      - MYSQL_PASSWORD=Pass.6854
    networks:
      - docker-network

  nginx-proxy:
    build:
      context: ./nginx/proxy
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker-network

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    environment:
      - DEFAULT_EMAIL=sinohiro966@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - docker-network
networks:
  docker-network:
    external:
      name: sinohiro-server

volumes:
  certs:
  vhost:
  html:
  acme:
  nextcloud:
    driver_opts:
      type: none
      device: /mnt/web/sinohiroHP-docker/nextcloud
      o: bind
  db: 
    driver_opts:
      type: none
      device: /mnt/web/sinohiroHP-docker/mariadb
      o: bind
  geekcast: 
    driver_opts:
      type: none
      device: /mnt/web/sinohiroHP-docker/geekcast
      o: bind
  geekcast-db: 
    driver_opts:
      type: none
      device: /mnt/web/sinohiroHP-docker/geekcast-db
      o: bind