version: "3"
services:
  dns:
    build: .
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "sinohiro.dip.jp:192.168.1.2"
    cap_add:
      - NET_ADMIN
